version: '3'
 
services:
  express: 
    container_name: blogster_express
    # build: .docker/docker-react.dockerfile
    build: 
      context: .
      dockerfile: .docker/express.dockerfile
    ports:
    - 5000:5000  
    volumes:
      # not override /app/node_modules
      - /app/node_modules
      - ./app:/app
    environment:
      DOCKER_CMP: "true"
    depends_on:
      - mongo
    networks:
      - blogster-net
    command: npm run dev

  mongo:
    container_name: blogster_mongo
    image: mongo
    volumes:
     - ./data/backup:/data/backup 
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: rootUser
    #   MONGO_INITDB_ROOT_PASSWORD: mongoPas123
    # ports:
    #   - 27017:27017
    networks:
        - blogster-net

  mongo-express:
    container_name: blogster_mongo_express
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: rootUser
      # ME_CONFIG_MONGODB_ADMINPASSWORD: mongoPas123
    depends_on:
      - mongo
    networks:
        - blogster-net
    
networks:
  blogster-net:
    driver: "bridge"